#!/usr/bin/env node

// "requires" used in this file ------------------------------------------------

var path = require('path'), fs = require('fs'), glob = require('glob');
var minimist = require('minimist');
var express = require('express');
var emi = require('express-middleware-image');
var bodyParser = require('body-parser');

var nconf = require('nconf');
var util = require('util');

// First consider commandline arguments and environment variables, respectively.
nconf.argv().env();

// Then load configuration from a designated file.
nconf.file({ file: 'config.json' });

// Parse command line args, if any ---------------------------------------------

var argv = minimist(process.argv.slice(2));

var photosDir = process.cwd();  // by default
if ('photos-dir' in argv) {
    photosDir = argv['photos-dir'];
}

var port = 8123; // by default
if ('p' in argv) {
    port = parseInt(argv['p']);
}

var cacheDir = '/Volumes/Storage/tmp/triage'; // by default
if ('cache-dir' in argv) {
    cacheDir = argv['cache-dir'];
}

// Load photo list -------------------------------------------------------------
var readPhotolist = function(dirname) {
	var jpegs = [];
	var ratingsFilePath = path.join(photosDir, dirname,'ratings.json');
	if ((fs.existsSync(ratingsFilePath)) && !('reset' in argv)) {
	    // Load ratings file if it exists, unless --reset is passed
	    jpegs = require(ratingsFilePath);
	    all_fnames = jpegs.map(function(entry) { return entry.fname; });
	    new_jpegs = glob.sync(
	        path.join(photosDir, dirname, '*.+(jpg|jpeg)'),
	        { nocase: true }
	    ).map(function(fname) {
	        return {
	            fname: fname.split(path.sep).slice(-1)[0],
	            rating: 0
	        };
	    }).filter(function(entry) {
	    	return all_fnames.indexOf(entry.fname) < 0;
	    });
	    if (new_jpegs.length > 0) {
	    	jpegs = jpegs.concat(new_jpegs);
	    }
	} else {
	    // Start from all zeros, load everything matching .jpg or .jpeg
	    jpegs = glob.sync(
	        path.join(photosDir, dirname, '*.+(jpg|jpeg)'),
	        { nocase: true }
	    ).map(function(fname) {
	        return {
	            fname: fname.split(path.sep).slice(-1)[0],
	            rating: 0
	        };
	    });
	}
	return jpegs;
};


// Save and exit functions -----------------------------------------------------
function save(dirname) {
	if ( ! dirname ) {
		return;
	}
    // write 2-space indented file
    fs.writeFileSync(path.join(photosDir, dirname,'ratings.json'), JSON.stringify(allJpegs[dirname], null, 2));
    console.log('saved');
}

function exit() {
    save();
    process.exit(0);
}
process.on('SIGINT', exit);

function getDirectories(path) {
  return fs.readdirSync(path).filter(function (file) {
    return fs.statSync(path+'/'+file).isDirectory();
  });
};

// Express server --------------------------------------------------------------
var app = express();

// Parse JSON posted to server
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
	extended: true
})); 
const allJpegs = {};

var middlewares = {};

var isActive = null;

app.use('/dir/:dirname/images/*',function(req, res, next) {
	clearTimeout(isActive);
	isActive = setTimeout(function() {
		tryUnmounting(rescanPhotos);
	},1000*60*30);
	var newurl = req.originalUrl.replace(/.*\/images/,'');
	var urlbits = newurl.split('/');
	urlbits[2] = req.params['dirname']+'/'+unescape(urlbits[2]);
	req.originalUrl = urlbits.join('/');
	next();
});

app.use(emi({
    root: photosDir,
    cache: cacheDir,
    rotate: true,
    quality: 60
}));

var rescanPhotos = function() {
	Object.keys(allJpegs).forEach(function(dir) {
		delete allJpegs[dir];
	});
	getDirectories(photosDir).forEach(function(dirname) {
		// Serve smaller images at /h:xxx/filename.jpg
		allJpegs[dirname] = readPhotolist(dirname);
	});	
};


app.get('/',function(req,res) {
	var wol = require('wake_on_lan');
	if ( ! host_up ) {
		wol.wake(nconf.get('nas_mac'));		
	}
	res.sendFile(path.join(__dirname , 'app','root.html'));
});

app.get('/receiver.html',function(req,res) {
	res.sendFile(path.join(__dirname , 'app','receiver.html'));
});

app.get('/dirs.json',function(req,res) {
	res.send(Object.keys(allJpegs));
});

// Static server for the angular.js app
app.use('/dir/:dirname/', express.static(path.join(__dirname , 'app')));

// A few URLs for front/back end communications --------------------------------
app.get('/dir/:dirname/photos.json', function(req, res){
  res.send(allJpegs[req.params['dirname']]);
});

app.post('/dir/:dirname/rate', function(req, res) {
    var index = parseInt(req.body.index);
    var rating = parseInt(req.body.rating);
    allJpegs[req.params['dirname']][index].rating = rating;
    res.send({});
});

app.post('/dir/:dirname/rate/reset', function(req, res) {
    for(var index=0; index < allJpegs.length; index++) {
        allJpegs[req.params['dirname']][index].rating = 0;
    }
    res.send({});
});

app.post('/dir/:dirname/rotate',function(req,res) {
	//1 none 6 counter-clockwise, 8 clockwise
	var direction = req.body.rotate;
	var orig_filename = allJpegs[req.params['dirname']][req.body.index].fname;
	var base_filename = orig_filename.replace(/\.JPG/i, '');
	var orig_file_path = path.join(photosDir, req.params['dirname'], orig_filename);
	var thumb_file_path = path.join(cacheDir, req.params['dirname'], base_filename+'_h800.jpg');
	//2015-03-01
	require('child_process').exec('/usr/bin/exiftool -Orientation='+direction+' -n '+orig_file_path,function() {
		var touch_date = new Date();
		touch_date.setTime(touch_date.getTime() - 1000*60*60*48);
		fs.utimes(thumb_file_path,touch_date,touch_date,function() {
			res.send({});
		});
	});
});

app.post('/dir/:dirname/save', function(req, res) {
    save(req.params['dirname']);
    res.send({});
});

var casting = require('./triage-cast');

rescanPhotos();


function testPort(port, host, cb) {
  require('net').createConnection(port, host).on("connect", function(e) {
    cb("success", e); 
  }).on("error", function(e) {
    cb("failure", e);
  });
};

var host_up = false;

var testHost = function() {
	testPort(445,nconf.get('nas_host'),function(state,error) {
		if (state == "success") {
			if (! host_up ) {
				console.log("Host now is online ",state);
			}
			host_up = true;			
		} else {
			if ( host_up ) {
				console.log("Host now offline ",state);
			}
			host_up = false;
		}
	});
};

var host_tester = function() {
	setTimeout(function() {
		testHost();
		setTimeout(arguments.callee,5000);
	},5000);
};

host_tester();

var mount_password = null;

var tryMounting = function(callback) {
	if ( ! mount_password ) {
		callback();
		return;
	}
	if ( ! host_up ) {
		callback();
		return;
	}
	require('./osx-mountutils').mount('//'+nconf.get('nas_username')+':'+mount_password+'@'+nconf.get('nas_host')+'/'+nconf.get('nas_path'),nconf.get('nas_mount_path'),{'fstype':'smbfs'},callback);
};

var tryUnmounting = function(callback) {
	mount_password = null;
	casting.state.enabled = false;
	require('./osx-mountutils').umount(nconf.get('nas_mount_path'),false,null,callback);
};

app.get('/logout',function(req,res) {
	tryUnmounting(function() {
		res.send({'status' : 'OK'});
		rescanPhotos();
	});
});

app.post('/login',function(req,res) {
	casting.state.enabled = true;
	mount_password = req.body['password'];
	tryMounting(function() {
		res.send({"status" : "OK"});
		rescanPhotos();
	});
});

// Fire up the server ----------------------------------------------------------
var server = app.listen(port, function() {
    console.log('Listening on port %d', server.address().port);
});
